language: node_js

node_js:
  - '10'
  - '12'

before_install:
  - npm install -g npm
  - npm --version

install:
  - npm install --force

after_success:
  - npm run coveralls
  - npm run coverage-clean
